# Generated by Django 5.2.11 on 2026-02-17 00:00

from django.db import migrations


def seed_about_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    PageSection = apps.get_model("pages", "PageSection")

    page, _ = Page.objects.get_or_create(
        slug="about",
        defaults={
            "title": "Обо мне",
            "subtitle": "История проекта, ценности и подход к работе с людьми и местом.",
            "is_published": True,
            "order": 0,
        },
    )

    if not page.title:
        page.title = "Обо мне"
    if not page.subtitle:
        page.subtitle = "История проекта, ценности и подход к работе с людьми и местом."
    page.is_published = True
    page.order = 0
    page.save(update_fields=["title", "subtitle", "is_published", "order", "updated_at"])

    PageSection.objects.filter(page=page).delete()

    PageSection.objects.bulk_create(
        [
            PageSection(
                page=page,
                title="Как появился проект",
                text=(
                    "Новое Конаково выросло из практики маленьких встреч и маршрутов по местам, "
                    "где можно замедлиться, услышать себя и побыть в живом диалоге с природой."
                ),
                order=0,
            ),
            PageSection(
                page=page,
                title="Во что я верю",
                text=(
                    "Мне важны бережность к человеку, уважение к ритму группы и ясная структура программы, "
                    "в которой есть место свободе, тишине и совместному опыту."
                ),
                order=1,
            ),
            PageSection(
                page=page,
                title="Что вы получите",
                text=(
                    "На странице и в программах вы найдете понятные форматы участия: от авторских маршрутов "
                    "до камерных практик, с прозрачной организацией и сопровождением."
                ),
                order=2,
            ),
        ]
    )


def unseed_about_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    PageSection = apps.get_model("pages", "PageSection")

    page = Page.objects.filter(slug="about").first()
    if not page:
        return
    PageSection.objects.filter(page=page).delete()
    page.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_about_page, reverse_code=unseed_about_page),
    ]
