# Generated by Django 6.0.2 on 2026-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Лиза Стручкова', max_length=255, verbose_name='Имя')),
                ('description', models.TextField(default='Делюсь событиями, тишиной и тёплыми практиками в Конаково.', verbose_name='Описание')),
                ('background_image', models.ImageField(upload_to='hero/background/', verbose_name='Фоновое изображение')),
                ('avatar', models.ImageField(upload_to='hero/avatar/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Hero-блок',
                'verbose_name_plural': 'Hero-блок',
            },
        ),
    ]
