# Generated by Django 5.2.11 on 2026-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('preview_description', models.TextField()),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видео')], max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья / Видео',
                'verbose_name_plural': 'Статьи и видео',
                'ordering': ['-created_at'],
            },
        ),
    ]
