# Generated by Django 5.2.11 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


SERVICE_SQL = """
CREATE TABLE IF NOT EXISTS core_service (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    slug VARCHAR(50),
    description TEXT NOT NULL DEFAULT '',
    is_category BOOLEAN NOT NULL DEFAULT FALSE,
    "order" INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    parent_id BIGINT NULL
);

ALTER TABLE core_service ADD COLUMN IF NOT EXISTS slug VARCHAR(50);
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS is_category BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE core_service ADD COLUMN IF NOT EXISTS parent_id BIGINT NULL;

UPDATE core_service
SET slug = CONCAT('service-', id)
WHERE slug IS NULL OR slug = '';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_service_parent_id_fk'
    ) THEN
        ALTER TABLE core_service
        ADD CONSTRAINT core_service_parent_id_fk
        FOREIGN KEY (parent_id) REFERENCES core_service (id)
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'core_service_slug_key'
    ) THEN
        CREATE UNIQUE INDEX core_service_slug_key ON core_service (slug);
    END IF;
END $$;
"""

TARIFF_SQL = """
CREATE TABLE IF NOT EXISTS core_tariff (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(50) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    duration VARCHAR(255) NOT NULL DEFAULT '',
    price INTEGER NOT NULL DEFAULT 0,
    "order" INTEGER NOT NULL DEFAULT 0,
    service_id BIGINT NOT NULL REFERENCES core_service (id) ON DELETE CASCADE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'core_tariff_service_slug_uniq'
    ) THEN
        CREATE UNIQUE INDEX core_tariff_service_slug_uniq ON core_tariff (service_id, slug);
    END IF;
END $$;
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS core_tariff;
DROP TABLE IF EXISTS core_service;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_news"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=SERVICE_SQL,
                    reverse_sql=REVERSE_SQL,
                ),
                migrations.RunSQL(
                    sql=TARIFF_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Service",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("is_active", models.BooleanField(default=True)),
                        ("slug", models.SlugField(unique=True)),
                        ("description", models.TextField(blank=True)),
                        ("is_category", models.BooleanField(default=False)),
                        ("order", models.PositiveIntegerField(default=0)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="children",
                                to="core.service",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["order"],
                    },
                ),
                migrations.CreateModel(
                    name="Tariff",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("slug", models.SlugField()),
                        ("description", models.TextField(blank=True)),
                        ("duration", models.CharField(blank=True, max_length=255)),
                        ("price", models.IntegerField()),
                        ("order", models.PositiveIntegerField(default=0)),
                        (
                            "service",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="tariffs",
                                to="core.service",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["order"],
                        "unique_together": {("service", "slug")},
                    },
                ),
            ],
        ),
    ]
