# Generated by Django 5.2.11 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


SCHEDULE_DAY_SQL = """
CREATE TABLE IF NOT EXISTS core_scheduleday (
    id BIGSERIAL PRIMARY KEY,
    date DATE,
    is_published BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE core_scheduleday ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE core_scheduleday ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT TRUE;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'core_scheduleday' AND column_name = 'title'
    ) THEN
        ALTER TABLE core_scheduleday ALTER COLUMN title SET DEFAULT '';
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'core_scheduleday' AND column_name = 'created_at'
    ) THEN
        ALTER TABLE core_scheduleday ALTER COLUMN created_at SET DEFAULT NOW();
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'core_scheduleday_date_uniq'
    ) THEN
        CREATE UNIQUE INDEX core_scheduleday_date_uniq ON core_scheduleday (date);
    END IF;
END $$;
"""


SCHEDULE_EVENT_SQL = """
CREATE TABLE IF NOT EXISTS core_scheduleevent (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL DEFAULT '',
    category VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    time_start TIME NOT NULL DEFAULT '00:00:00',
    time_end TIME NOT NULL DEFAULT '00:00:00',
    price INTEGER NULL,
    color VARCHAR(20) NOT NULL DEFAULT '',
    "order" INTEGER NOT NULL DEFAULT 0,
    day_id BIGINT NOT NULL REFERENCES core_scheduleday (id) ON DELETE CASCADE,
    service_id BIGINT NULL REFERENCES core_service (id) ON DELETE SET NULL
);

ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS category VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS time_start TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS time_end TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS price INTEGER NULL;
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS color VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS day_id BIGINT NULL;
ALTER TABLE core_scheduleevent ADD COLUMN IF NOT EXISTS service_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_scheduleevent_day_id_fk'
    ) THEN
        ALTER TABLE core_scheduleevent
        ADD CONSTRAINT core_scheduleevent_day_id_fk
        FOREIGN KEY (day_id) REFERENCES core_scheduleday (id)
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_scheduleevent_service_id_fk'
    ) THEN
        ALTER TABLE core_scheduleevent
        ADD CONSTRAINT core_scheduleevent_service_id_fk
        FOREIGN KEY (service_id) REFERENCES core_service (id)
        ON DELETE SET NULL;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_service_tariff"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=SCHEDULE_DAY_SQL, reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=SCHEDULE_EVENT_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ScheduleDay",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("date", models.DateField(unique=True)),
                        ("is_published", models.BooleanField(default=True)),
                    ],
                    options={
                        "ordering": ["date"],
                    },
                ),
                migrations.CreateModel(
                    name="ScheduleEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("category", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        ("time_start", models.TimeField()),
                        ("time_end", models.TimeField()),
                        ("price", models.IntegerField(blank=True, null=True)),
                        ("color", models.CharField(blank=True, max_length=20)),
                        ("order", models.PositiveIntegerField(default=0)),
                        (
                            "day",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="events",
                                to="core.scheduleday",
                            ),
                        ),
                        (
                            "service",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="core.service",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["time_start", "order"],
                    },
                ),
            ],
        ),
    ]
