# Generated by Django 5.2.11 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_scheduleday_scheduleevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="schedule_events/",
                verbose_name="Изображение",
            ),
        ),
    ]
